export const VERSION = "0.10.1";

export const DEFAULT_DB_DIR = ".graphward";
export const DEFAULT_DB_NAME = "index.sqlite";

export const IGNORED_DIRECTORIES = new Set([
  ".git",
  ".hg",
  ".svn",
  ".agents",
  ".claude",
  ".codex",
  ".cursor",
  ".idea",
  ".graphward",
  ".memdb",
  ".memtrace",
  ".next",
  ".nuxt",
  ".venv",
  ".vscode",
  "__pycache__",
  "build",
  "coverage",
  "dist",
  "node_modules",
  "out",
  "target",
  "vendor",
]);

export const SOURCE_EXTENSIONS = new Map([
  [".c", "c"],
  [".cc", "cpp"],
  [".cpp", "cpp"],
  [".cs", "csharp"],
  [".cxx", "cpp"],
  [".go", "go"],
  [".h", "c"],
  [".hpp", "cpp"],
  [".java", "java"],
  [".js", "javascript"],
  [".jsx", "javascript"],
  [".kt", "kotlin"],
  [".kts", "kotlin"],
  [".mjs", "javascript"],
  [".mts", "typescript"],
  [".php", "php"],
  [".py", "python"],
  [".rb", "ruby"],
  [".rs", "rust"],
  [".swift", "swift"],
  [".ts", "typescript"],
  [".tsx", "typescript"],
]);

export const CALL_KEYWORDS = new Set([
  "assert",
  "await",
  "catch",
  "class",
  "def",
  "delete",
  "do",
  "else",
  "except",
  "finally",
  "for",
  "foreach",
  "function",
  "if",
  "import",
  "in",
  "isinstance",
  "lambda",
  "match",
  "new",
  "print",
  "raise",
  "return",
  "sizeof",
  "super",
  "switch",
  "typeof",
  "unless",
  "using",
  "while",
  "with",
  "yield",
]);

export const SUPPORTED_PROTOCOLS = [
  "2025-11-25",
  "2025-06-18",
  "2025-03-26",
  "2024-11-05",
];

export const DEFAULT_PROTOCOL = SUPPORTED_PROTOCOLS[0];
